# Generated by Django 4.2.11 on 2024-04-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='occurence',
            field=models.IntegerField(default=1),
        ),
    ]
